version: '3.1'

services:

  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass ${REDIS_PASS} --appendonly yes
    restart: always
    ports:
      - 6379:6379
    network_mode: "host"


  tgbot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python main.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"
    depends_on:
      - redis

